version: '3.8'
services:
  frontend:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - aed-consoleadmin:/var/www/html
# Names the volume
volumes:
  aed-consoleadmin: